### PR TITLE
Create Chinese translation strings.xml

### PR DESCRIPTION
**Pull request by Tribbtsz**

### CODE REVIEW

**Review by Enigma1309 — APPROVED** [review]
lgtm

**Comment by 25huizengek1** [comment]
@Tribbtsz Why are you pushing changes that are not related to this PR at all? Detekt shouldn't have to be disabled in order to push some translations??

I am able to cherry-pick your translations onto ViTune master, if you want.

**Comment by 25huizengek1** [comment]
@Tribbtsz I'm sorry, I see that you tried out GitHub workflows in order to test this yourself, then tried to delete it by creating a delete commit. I guess I can squash and merge this PR, let me review the actual translations...

**Comment by 25huizengek1** [comment]
Please do note though that full Chinese support is not possible, as YouTube Music is not available in China and therefore doesn't provide Chinese content. (closes #359)

**Comment by Tribbtsz** [comment]
Oh my goodness, this is not what I wanted. I messed everything up. The subsequent commits were not what I intended. I was trying to do some testing in the repository I had forked (attempting to use workflow to package the APK), but I didn't realize these commits would affect this PR. If possible, could you please only focus on the changes in the string.xml file and ignore the other commits? Or do I need to redo the previous steps?

**Review by 25huizengek1 — APPROVED** [review]
LGTM! Thank you so much for the translations! I've formatted a bit so we can squash.

**Pull request merged**
