### PR TITLE
Add French translations

### PR DESCRIPTION
**Pull request by Mickael81**

### CODE REVIEW

**Comment by Wqttzicue** [comment]
Uh, the filepath is messed up, but im pretty sure Ingek can easily put all in correct place

**Comment by Wqttzicue** [comment]
You did great work

**Comment by Mickael81** [comment]
Thank you very much. I renamed the file "values-fr" to "strings.xml" but I was not able to create the folder "values-fr" as it was done for the other languages. I was trying to move the file "strings.xml" to the folder "values -fr".

**Comment by Wqttzicue** [comment]
> Thank you very much. I renamed the file "values-fr" to "strings.xml" but I was not able to create the folder "values-fr" as it was done for the other languages. I was trying to move the file "strings.xml" to the folder "values -fr".

To make folder you need to add into name
Like
Path : src/
Add file
Name : "strings.xml"
Result src/strings.xml


Path : src/
Add file
Name : "values-fr/strings.xml"
Result src/values-fr/strings.xml

Adding dash in files name makes folder for it.

**Comment by 25huizengek1** [comment]
@Mickael81 Thank you so much for the translations!

**Pull request merged**
